package com.dachser.profit.adapter.incoming.web;

import com.dachser.profit.adapter.incoming.web.dto.ProfitResponse;
import com.dachser.profit.domain.model.ProfitCalculation;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

/**
 * Maps domain {@link ProfitCalculation}s to web {@link ProfitResponse} DTOs, flattening the nested
 * {@link com.dachser.profit.domain.model.ProfitResult}. Implementation is generated by MapStruct at
 * build time and registered as a Spring bean ({@code componentModel = "spring"}).
 */
@Mapper(componentModel = "spring")
public interface ProfitWebMapper {

  @Mapping(target = "income", source = "result.totalIncome")
  @Mapping(target = "totalCosts", source = "result.totalCost")
  @Mapping(target = "profitOrLoss", source = "result.profitOrLoss")
  @Mapping(target = "profit", source = "result.profit")
  ProfitResponse toResponse(ProfitCalculation calculation);
}
