-- Customer payments for a shipment (the income side of the profit equation).
CREATE TABLE income (
    id          BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id BIGINT        NOT NULL,
    amount      DECIMAL(12,2) NOT NULL,
    CONSTRAINT fk_income_shipment FOREIGN KEY (shipment_id) REFERENCES shipment (id) ON DELETE CASCADE,
    CONSTRAINT chk_income_amount CHECK (amount >= 0)
);
CREATE INDEX idx_income_shipment ON income (shipment_id);
