-- Service costs for a shipment (the cost side of the profit equation). `cost_type` distinguishes
-- the main carriage cost from any additional cost.
CREATE TABLE cost (
    id          BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id BIGINT        NOT NULL,
    amount      DECIMAL(12,2) NOT NULL,
    cost_type   VARCHAR(20)   NOT NULL,
    CONSTRAINT fk_cost_shipment FOREIGN KEY (shipment_id) REFERENCES shipment (id) ON DELETE CASCADE,
    CONSTRAINT chk_cost_amount CHECK (amount >= 0),
    CONSTRAINT chk_cost_type CHECK (cost_type IN ('MAIN', 'ADDITIONAL'))
);
CREATE INDEX idx_cost_shipment ON cost (shipment_id);
