-- A shipment: the unit of work whose profit/loss we evaluate. `reference` is the business
-- identifier shown in the UI (e.g. '0001'); the surrogate `id` is the primary key.
CREATE TABLE shipment (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference   VARCHAR(50)  NOT NULL,
    description VARCHAR(255),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_shipment_reference UNIQUE (reference)
);
